#!/usr/bin/env bash
# Regenerates .claude/claude.md - the single-file bundle for harnesses that load
# one config file (e.g. Claude.ai Personal Preferences). It concatenates the four
# source files in order. Claude Code itself does not need this file; it reads the
# same sources live via the @import directives in the root CLAUDE.md.
#
# Run by .github/workflows/build-claude-bundle.yml on change to any source.
# Also runnable locally: bash .claude/build-claude-bundle.sh
set -euo pipefail

cd "$(dirname "$0")/.."   # repo root

OUT=".claude/claude.md"
SOURCES=(
  ".claude/claude-code-agent.md"
  "agent.md"
  ".claude/claude-sp-guards.md"
  "agent-prompt-discipline.md"
)

for f in "${SOURCES[@]}"; do
  [ -f "$f" ] || { echo "ERROR: missing source: $f" >&2; exit 1; }
done

{
  echo "<!-- GENERATED FILE - DO NOT EDIT."
  echo "     Regenerated by .claude/build-claude-bundle.sh from, in order:"
  for f in "${SOURCES[@]}"; do echo "       - $f"; done
  echo "     Edit the sources; the build-claude-bundle workflow regenerates this. -->"
  for f in "${SOURCES[@]}"; do
    printf '\n\n---\n\n'
    cat "$f"
  done
} > "$OUT"

echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
